# Generated by Django 5.0.2 on 2024-02-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="pincode",
            field=models.DecimalField(decimal_places=0, default=123456, max_digits=6),
            preserve_default=False,
        ),
    ]
